#-------------------------------------------------
#
# Project created by QtCreator 2011-12-21T13:34:30
#
#-------------------------------------------------
TARGET = ilwiscore
TEMPLATE = lib

include(global.pri)

QT       += sql xmlpatterns

DEFINES += CORE_LIBRARY

SOURCES += core/kernel.cpp \
    core/version.cpp \
    core/module.cpp \
    core/errorobject.cpp \
    core/abstractfactory.cpp \
    core/ilwisobjects/ilwisobject.cpp \
    core/ilwisobjects/geometry/coordinatesystem/coordinatesystem.cpp \
    core/ilwisobjects/geometry/georeference/georeference.cpp \
    core/ilwisobjects/geometry/georeference/simpelgeoreference.cpp \
    core/ilwisobjects/geometry/georeference/cornersgeoreference.cpp \
    core/ilwisobjects/coverage/coverage.cpp \
    core/publicdatabase.cpp \
    core/ilwisobjects/ilwisobjectfactory.cpp \
    core/issuelogger.cpp \
    core/identity.cpp \
    core/ilwisobjects/domain/domain.cpp \
    core/ilwisobjects/domain/thematicitem.cpp \
    core/util/range.cpp \
    core/catalog/catalog.cpp \
    core/catalog/catalogconnector.cpp \
    core/connectorfactory.cpp \
    core/ilwiscontext.cpp \
    core/catalog/mastercatalog.cpp \
    core/catalog/catalogquery.cpp \
    core/catalog/resource.cpp \
    core/ilwisobjects/ilwisobjectconnector.cpp \
    core/ilwisobjects/geometry/coordinatesystem/conventionalcoordinatesystem.cpp \
    core/util/juliantime.cpp \
    core/ilwisobjects/domain/numericdomain.cpp \
    core/ilwisobjects/domain/identifierrange.cpp \
    core/ilwisobjects/domain/identifieritem.cpp \
    core/ilwisobjects/domain/itemrange.cpp \
    core/ilwisobjects/coverage/featurecoverage.cpp \
    core/ilwisobjects/coverage/feature.cpp \
    core/ilwisobjects/coverage/grid.cpp \
    core/ilwisobjects/coverage/pixeliterator.cpp \
    core/ilwisobjects/table/flattable.cpp \
    core/ilwisobjects/table/columndefinition.cpp \
    core/ilwisobjects/coverage/featureiterator.cpp \
    core/ilwisobjects/table/basetable.cpp \
    core/ilwisobjects/coverage/featurefactory.cpp \
    core/ilwisobjects/geometry/coordinatesystem/projectionimplementation.cpp \
    core/ilwisobjects/geometry/coordinatesystem/projection.cpp \
    core/ilwisobjects/geometry/coordinatesystem/proj4parameters.cpp \
    core/ilwisobjects/geometry/coordinatesystem/ellipsoid.cpp \
    core/ilwisobjects/geometry/coordinatesystem/geodeticdatum.cpp \
    core/ilwisobjects/operation/operation.cpp \
    core/ilwisobjects/operation/operationmetadata.cpp \
    core/ilwisobjects/operation/operationExpression.cpp \
    core/ilwisobjects/operation/commandhandler.cpp \
    core/ilwisobjects/coverage/blockiterator.cpp \
    core/util/locker.cpp \
    core/ilwisobjects/domain/datadefinition.cpp \
    core/ilwisobjects/geometry/georeference/ctpgeoreference.cpp \
    core/ilwisobjects/geometry/georeference/controlpoint.cpp \
    core/ilwisobjects/geometry/georeference/planarctpgeoreference.cpp \
    core/util/mathhelper.cpp \
    core/ilwisobjects/domain/textdomain.cpp \
    core/ilwisobjects/geometry/georeference/georefadapter.cpp \
    core/ilwisobjects/operation/symboltable.cpp \
    core/ilwisobjects/operation/operationhelpergrid.cpp \
    core/ilwisobjects/operation/operationhelper.cpp \
    core/ilwisobjects/operation/operationhelperfeatures.cpp \
    core/ilwisobjects/geometry/georeference/georefimplementation.cpp \
    core/ilwisobjects/geometry/georeference/georefimplementationfactory.cpp \
    core/ilwisobjects/domain/coordinatedomain.cpp \
    core/ilwisobjects/coverage/indexslicer.cpp \
    core/ilwisobjects/coverage/rastercoverage.cpp \
    core/ilwisobjects/coverage/rasterinterpolator.cpp \
    core/ilwisobjects/operation/logicalexpressionparser.cpp \
    core/ilwisobjects/table/tableselector.cpp \
    core/ilwisobjects/table/tablemerger.cpp \
    core/ilwisobjects/domain/domainmerger.cpp \
    core/util/tranquilizer.cpp \
    core/ilwisobjects/operation/numericoperation.cpp \
    core/ilwisobjects/geometry/coordinatesystem/csytransform.cpp \
    core/ilwisobjects/coverage/geometryhelper.cpp \
    core/ilwisobjects/operation/rasterfilter.cpp \
    core/catalog/dataformat.cpp \
    core/ilwisobjects/domain/domainhelper.cpp \
    core/ilwisobjects/domain/numericrange.cpp \
    core/ilwisobjects/domain/colordomain.cpp \
    core/ilwisobjects/domain/colorrange.cpp \
    core/catalog/catalogexplorer.cpp \
    core/catalog/foldercatalogexplorer.cpp \
    core/catalog/catalogview.cpp \
    core/ilwisobjects/coverage/vertexiterator.cpp \
    core/ilwisobjects/domain/coloritem.cpp \
    core/oshelper.cpp \
    core/ilwisobjects/operation/operationoverloads.cpp \
    core/ilwisobjects/operation/classification/featurespace.cpp \
    core/ilwisobjects/operation/classification/sampleset.cpp \
    core/ilwisobjects/operation/classification/samplestatistics.cpp \
    core/ilwisobjects/domain/interval.cpp \
    core/ilwisobjects/domain/intervalrange.cpp \
    core/ilwisobjects/geometry/georeference/undeterminedgeoreference.cpp \
    core/ilwisobjects/geometry/coordinatesystem/boundsonlycoordinatesystem.cpp \
    core/catalog/dataset.cpp \
    core/util/bresenham.cpp \
    core/util/xpathparser.cpp \
    core/util/xmlstreamparser.cpp \
    core/util/ilwisconfiguration.cpp \
    core/util/supportlibraryloader.cpp \
    core/iooptions.cpp \
    core/ilwisobjects/table/record.cpp \
    core/ilwisobjects/table/attributedefinition.cpp \
    core/ilwisobjects/table/attributetable.cpp \
    core/ilwisobjects/table/selectabletable.cpp \
    core/ilwistypes.cpp \
    core/identityinterface.cpp \
    core/ilwisobjects/representation/representation.cpp \
    core/ilwisobjects/representation/colorlookup.cpp \
    core/ilwisobjects/representation/continuouscolorlookup.cpp \
    core/ilwisobjects/representation/palettecolorlookup.cpp \
    core/ilwisobjects/operation/modeller/workflow.cpp \
    core/util/tranquilizerfactory.cpp \
    core/util/consoletranquilizer.cpp \
    core/ilwisobjects/representation/shapelookup.cpp \
    core/internaldatabaseconnection.cpp \
    core/catalog/mastercatalogcache.cpp \
    core/catalog/catalogexplorerworker.cpp \
    core/ilwisobjects/operation/script.cpp \
    core/geos/include/geos/algorithm/ConvexHull.inl \
    core/geos/include/geos/geom/Coordinate.inl \
    core/geos/include/geos/geom/CoordinateArraySequenceFactory.inl \
    core/geos/include/geos/geom/Envelope.inl \
    core/geos/include/geos/geom/GeometryCollection.inl \
    core/geos/include/geos/geom/GeometryFactory.inl \
    core/geos/include/geos/geom/LineSegment.inl \
    core/geos/include/geos/geom/MultiLineString.inl \
    core/geos/include/geos/geom/MultiPolygon.inl \
    core/geos/include/geos/geom/PrecisionModel.inl \
    core/geos/include/geos/geomgraph/DirectedEdge.inl \
    core/geos/include/geos/geomgraph/GeometryGraph.inl \
    core/geos/include/geos/io/ByteOrderDataInStream.inl \
    core/geos/include/geos/io/WKTReader.inl \
    core/geos/include/geos/noding/snapround/HotPixel.inl \
    core/geos/include/geos/noding/MCIndexNoder.inl \
    core/geos/include/geos/operation/overlay/MinimalEdgeRing.inl \
    core/geos/src/algorithm/distance/DiscreteHausdorffDistance.cpp \
    core/geos/src/algorithm/distance/DistanceToPoint.cpp \
    core/geos/src/algorithm/locate/IndexedPointInAreaLocator.cpp \
    core/geos/src/algorithm/locate/PointOnGeometryLocator.cpp \
    core/geos/src/algorithm/locate/SimplePointInAreaLocator.cpp \
    core/geos/src/algorithm/Angle.cpp \
    core/geos/src/algorithm/BoundaryNodeRule.cpp \
    core/geos/src/algorithm/Centroid.cpp \
    core/geos/src/algorithm/CentroidArea.cpp \
    core/geos/src/algorithm/CentroidLine.cpp \
    core/geos/src/algorithm/CentroidPoint.cpp \
    core/geos/src/algorithm/CGAlgorithms.cpp \
    core/geos/src/algorithm/ConvexHull.cpp \
    core/geos/src/algorithm/HCoordinate.cpp \
    core/geos/src/algorithm/InteriorPointArea.cpp \
    core/geos/src/algorithm/InteriorPointLine.cpp \
    core/geos/src/algorithm/InteriorPointPoint.cpp \
    core/geos/src/algorithm/LineIntersector.cpp \
    core/geos/src/algorithm/MCPointInRing.cpp \
    core/geos/src/algorithm/MinimumDiameter.cpp \
    core/geos/src/algorithm/NotRepresentableException.cpp \
    core/geos/src/algorithm/PointLocator.cpp \
    core/geos/src/algorithm/RayCrossingCounter.cpp \
    core/geos/src/algorithm/RobustDeterminant.cpp \
    core/geos/src/algorithm/SimplePointInRing.cpp \
    core/geos/src/algorithm/SIRtreePointInRing.cpp \
    core/geos/src/geom/prep/AbstractPreparedPolygonContains.cpp \
    core/geos/src/geom/prep/BasicPreparedGeometry.cpp \
    core/geos/src/geom/prep/PreparedGeometry.cpp \
    core/geos/src/geom/prep/PreparedGeometryFactory.cpp \
    core/geos/src/geom/prep/PreparedLineString.cpp \
    core/geos/src/geom/prep/PreparedLineStringIntersects.cpp \
    core/geos/src/geom/prep/PreparedPoint.cpp \
    core/geos/src/geom/prep/PreparedPolygon.cpp \
    core/geos/src/geom/prep/PreparedPolygonContains.cpp \
    core/geos/src/geom/prep/PreparedPolygonContainsProperly.cpp \
    core/geos/src/geom/prep/PreparedPolygonCovers.cpp \
    core/geos/src/geom/prep/PreparedPolygonIntersects.cpp \
    core/geos/src/geom/prep/PreparedPolygonPredicate.cpp \
    core/geos/src/geom/util/ComponentCoordinateExtracter.cpp \
    core/geos/src/geom/util/CoordinateOperation.cpp \
    core/geos/src/geom/util/GeometryCombiner.cpp \
    core/geos/src/geom/util/GeometryEditor.cpp \
    core/geos/src/geom/util/GeometryTransformer.cpp \
    core/geos/src/geom/util/LinearComponentExtracter.cpp \
    core/geos/src/geom/util/PointExtracter.cpp \
    core/geos/src/geom/util/PolygonExtracter.cpp \
    core/geos/src/geom/util/ShortCircuitedGeometryVisitor.cpp \
    core/geos/src/geom/util/SineStarFactory.cpp \
    core/geos/src/geom/Coordinate.cpp \
    core/geos/src/geom/CoordinateArraySequence.cpp \
    core/geos/src/geom/CoordinateArraySequenceFactory.cpp \
    core/geos/src/geom/CoordinateSequence.cpp \
    core/geos/src/geom/CoordinateSequenceFactory.cpp \
    core/geos/src/geom/Dimension.cpp \
    core/geos/src/geom/Envelope.cpp \
    core/geos/src/geom/Geometry.cpp \
    core/geos/src/geom/GeometryCollection.cpp \
    core/geos/src/geom/GeometryComponentFilter.cpp \
    core/geos/src/geom/GeometryFactory.cpp \
    core/geos/src/geom/GeometryList.cpp \
    core/geos/src/geom/IntersectionMatrix.cpp \
    core/geos/src/geom/LinearRing.cpp \
    core/geos/src/geom/LineSegment.cpp \
    core/geos/src/geom/LineString.cpp \
    core/geos/src/geom/Location.cpp \
    core/geos/src/geom/MultiLineString.cpp \
    core/geos/src/geom/MultiPoint.cpp \
    core/geos/src/geom/MultiPolygon.cpp \
    core/geos/src/geom/Point.cpp \
    core/geos/src/geom/Polygon.cpp \
    core/geos/src/geom/PrecisionModel.cpp \
    core/geos/src/geom/Triangle.cpp \
    core/geos/src/geomgraph/index/MonotoneChainEdge.cpp \
    core/geos/src/geomgraph/index/MonotoneChainIndexer.cpp \
    core/geos/src/geomgraph/index/SegmentIntersector.cpp \
    core/geos/src/geomgraph/index/SimpleEdgeSetIntersector.cpp \
    core/geos/src/geomgraph/index/SimpleMCSweepLineIntersector.cpp \
    core/geos/src/geomgraph/index/SimpleSweepLineIntersector.cpp \
    core/geos/src/geomgraph/index/SweepLineEvent.cpp \
    core/geos/src/geomgraph/index/SweepLineSegment.cpp \
    core/geos/src/geomgraph/Depth.cpp \
    core/geos/src/geomgraph/DirectedEdge.cpp \
    core/geos/src/geomgraph/DirectedEdgeStar.cpp \
    core/geos/src/geomgraph/EdgeEnd.cpp \
    core/geos/src/geomgraph/EdgeEndStar.cpp \
    core/geos/src/geomgraph/EdgeGeomGraph.cpp \
    core/geos/src/geomgraph/EdgeIntersectionList.cpp \
    core/geos/src/geomgraph/EdgeList.cpp \
    core/geos/src/geomgraph/EdgeNodingValidator.cpp \
    core/geos/src/geomgraph/EdgeRing.cpp \
    core/geos/src/geomgraph/GeometryGraph.cpp \
    core/geos/src/geomgraph/GraphComponent.cpp \
    core/geos/src/geomgraph/Label.cpp \
    core/geos/src/geomgraph/NodeFactory.cpp \
    core/geos/src/geomgraph/NodeGeomGraph.cpp \
    core/geos/src/geomgraph/NodeMap.cpp \
    core/geos/src/geomgraph/PlanarGraphGG.cpp \
    core/geos/src/geomgraph/Position.cpp \
    core/geos/src/geomgraph/Quadrant.cpp \
    core/geos/src/geomgraph/TopologyLocation.cpp \
    core/geos/src/index/bintree/Bintree.cpp \
    core/geos/src/index/bintree/IntervalBinTree.cpp \
    core/geos/src/index/bintree/KeyBinTree.cpp \
    core/geos/src/index/bintree/NodeBaseBinTree.cpp \
    core/geos/src/index/bintree/NodeBinTree.cpp \
    core/geos/src/index/bintree/RootBinTree.cpp \
    core/geos/src/index/chain/MonotoneChain.cpp \
    core/geos/src/index/chain/MonotoneChainBuilder.cpp \
    core/geos/src/index/chain/MonotoneChainOverlapAction.cpp \
    core/geos/src/index/chain/MonotoneChainSelectAction.cpp \
    core/geos/src/index/intervalrtree/IntervalRTreeBranchNode.cpp \
    core/geos/src/index/intervalrtree/IntervalRTreeLeafNode.cpp \
    core/geos/src/index/intervalrtree/IntervalRTreeNode.cpp \
    core/geos/src/index/intervalrtree/SortedPackedIntervalRTree.cpp \
    core/geos/src/index/quadtree/DoubleBits.cpp \
    core/geos/src/index/quadtree/IntervalSize.cpp \
    core/geos/src/index/quadtree/KeyQuadTree.cpp \
    core/geos/src/index/quadtree/NodeBaseQuadTree.cpp \
    core/geos/src/index/quadtree/NodeQuadTree.cpp \
    core/geos/src/index/quadtree/Quadtree.cpp \
    core/geos/src/index/quadtree/RootQuadTree.cpp \
    core/geos/src/index/strtree/AbstractNode.cpp \
    core/geos/src/index/strtree/AbstractSTRtree.cpp \
    core/geos/src/index/strtree/IntervalStree.cpp \
    core/geos/src/index/strtree/ItemBoundable.cpp \
    core/geos/src/index/strtree/SIRtree.cpp \
    core/geos/src/index/strtree/STRtree.cpp \
    core/geos/src/index/sweepline/SweepLineEventSL.cpp \
    core/geos/src/index/sweepline/SweepLineIndex.cpp \
    core/geos/src/index/sweepline/SweepLineInterval.cpp \
    core/geos/src/io/ByteOrderDataInStream.cpp \
    core/geos/src/io/ByteOrderValues.cpp \
    core/geos/src/io/CLocalizer.cpp \
    core/geos/src/io/ParseException.cpp \
    core/geos/src/io/StringTokenizer.cpp \
    core/geos/src/io/Unload.cpp \
    core/geos/src/io/WKBReader.cpp \
    core/geos/src/io/WKBWriter.cpp \
    core/geos/src/io/WKTReader.cpp \
    core/geos/src/io/WKTWriter.cpp \
    core/geos/src/io/Writer.cpp \
    core/geos/src/linearref/ExtractLineByLocation.cpp \
    core/geos/src/linearref/LengthIndexedLine.cpp \
    core/geos/src/linearref/LengthIndexOfPoint.cpp \
    core/geos/src/linearref/LengthLocationMap.cpp \
    core/geos/src/linearref/LinearGeometryBuilder.cpp \
    core/geos/src/linearref/LinearIterator.cpp \
    core/geos/src/linearref/LinearLocation.cpp \
    core/geos/src/linearref/LocationIndexOfLine.cpp \
    core/geos/src/linearref/LocationIndexOfPoint.cpp \
    core/geos/src/noding/snapround/HotPixel.cpp \
    core/geos/src/noding/snapround/MCIndexPointSnapper.cpp \
    core/geos/src/noding/snapround/MCIndexSnapRounder.cpp \
    core/geos/src/noding/snapround/SimpleSnapRounder.cpp \
    core/geos/src/noding/BasicSegmentString.cpp \
    core/geos/src/noding/FastNodingValidator.cpp \
    core/geos/src/noding/FastSegmentSetIntersectionFinder.cpp \
    core/geos/src/noding/GeometryNoder.cpp \
    core/geos/src/noding/IntersectionAdder.cpp \
    core/geos/src/noding/IntersectionFinderAdder.cpp \
    core/geos/src/noding/IteratedNoder.cpp \
    core/geos/src/noding/MCIndexNoder.cpp \
    core/geos/src/noding/MCIndexSegmentSetMutualIntersector.cpp \
    core/geos/src/noding/NodedSegmentString.cpp \
    core/geos/src/noding/NodingValidator.cpp \
    core/geos/src/noding/Octant.cpp \
    core/geos/src/noding/OrientedCoordinateArray.cpp \
    core/geos/src/noding/ScaledNoder.cpp \
    core/geos/src/noding/SegmentIntersectionDetector.cpp \
    core/geos/src/noding/SegmentNode.cpp \
    core/geos/src/noding/SegmentNodeList.cpp \
    core/geos/src/noding/SegmentString.cpp \
    core/geos/src/noding/SegmentStringUtil.cpp \
    core/geos/src/noding/SimpleNoder.cpp \
    core/geos/src/noding/SingleInteriorIntersectionFinder.cpp \
    core/geos/src/operation/buffer/BufferBuilder.cpp \
    core/geos/src/operation/buffer/BufferInputLineSimplifier.cpp \
    core/geos/src/operation/buffer/BufferOp.cpp \
    core/geos/src/operation/buffer/BufferParameters.cpp \
    core/geos/src/operation/buffer/BufferSubgraph.cpp \
    core/geos/src/operation/buffer/OffsetCurveBuilder.cpp \
    core/geos/src/operation/buffer/OffsetCurveSetBuilder.cpp \
    core/geos/src/operation/buffer/OffsetSegmentGenerator.cpp \
    core/geos/src/operation/buffer/RightmostEdgeFinder.cpp \
    core/geos/src/operation/buffer/SubgraphDepthLocater.cpp \
    core/geos/src/operation/distance/ConnectedElementLocationFilter.cpp \
    core/geos/src/operation/distance/ConnectedElementPointFilter.cpp \
    core/geos/src/operation/distance/DistanceOp.cpp \
    core/geos/src/operation/distance/GeometryLocation.cpp \
    core/geos/src/operation/intersection/Rectangle.cpp \
    core/geos/src/operation/intersection/RectangleIntersection.cpp \
    core/geos/src/operation/intersection/RectangleIntersectionBuilder.cpp \
    core/geos/src/operation/linemerge/EdgeString.cpp \
    core/geos/src/operation/linemerge/LineMergeDirectedEdge.cpp \
    core/geos/src/operation/linemerge/LineMergeEdge.cpp \
    core/geos/src/operation/linemerge/LineMergeGraph.cpp \
    core/geos/src/operation/linemerge/LineMerger.cpp \
    core/geos/src/operation/linemerge/LineSequencer.cpp \
    core/geos/src/operation/overlay/snap/GeometrySnapper.cpp \
    core/geos/src/operation/overlay/snap/LineStringSnapper.cpp \
    core/geos/src/operation/overlay/snap/SnapIfNeededOverlayOp.cpp \
    core/geos/src/operation/overlay/snap/SnapOverlayOp.cpp \
    core/geos/src/operation/overlay/validate/FuzzyPointLocator.cpp \
    core/geos/src/operation/overlay/validate/OffsetPointGenerator.cpp \
    core/geos/src/operation/overlay/validate/OverlayResultValidator.cpp \
    core/geos/src/operation/overlay/EdgeSetNoder.cpp \
    core/geos/src/operation/overlay/ElevationMatrix.cpp \
    core/geos/src/operation/overlay/ElevationMatrixCell.cpp \
    core/geos/src/operation/overlay/LineBuilder.cpp \
    core/geos/src/operation/overlay/MaximalEdgeRing.cpp \
    core/geos/src/operation/overlay/MinimalEdgeRing.cpp \
    core/geos/src/operation/overlay/OverlayNodeFactory.cpp \
    core/geos/src/operation/overlay/OverlayOp.cpp \
    core/geos/src/operation/overlay/PointBuilder.cpp \
    core/geos/src/operation/overlay/PolygonBuilder.cpp \
    core/geos/src/operation/polygonize/EdgeRingPologonize.cpp \
    core/geos/src/operation/polygonize/PolygonizeDirectedEdge.cpp \
    core/geos/src/operation/polygonize/PolygonizeEdge.cpp \
    core/geos/src/operation/polygonize/PolygonizeGraph.cpp \
    core/geos/src/operation/polygonize/Polygonizer.cpp \
    core/geos/src/operation/predicate/RectangleContains.cpp \
    core/geos/src/operation/predicate/RectangleIntersects.cpp \
    core/geos/src/operation/predicate/SegmentIntersectionTester.cpp \
    core/geos/src/operation/relate/EdgeEndBuilder.cpp \
    core/geos/src/operation/relate/EdgeEndBundle.cpp \
    core/geos/src/operation/relate/EdgeEndBundleStar.cpp \
    core/geos/src/operation/relate/RelateComputer.cpp \
    core/geos/src/operation/relate/RelateNode.cpp \
    core/geos/src/operation/relate/RelateNodeFactory.cpp \
    core/geos/src/operation/relate/RelateNodeGraph.cpp \
    core/geos/src/operation/relate/RelateOp.cpp \
    core/geos/src/operation/sharedpaths/SharedPathsOp.cpp \
    core/geos/src/operation/union/CascadedPolygonUnion.cpp \
    core/geos/src/operation/union/CascadedUnion.cpp \
    core/geos/src/operation/union/PointGeometryUnion.cpp \
    core/geos/src/operation/union/UnaryUnionOp.cpp \
    core/geos/src/operation/valid/ConnectedInteriorTester.cpp \
    core/geos/src/operation/valid/ConsistentAreaTester.cpp \
    core/geos/src/operation/valid/IndexedNestedRingTester.cpp \
    core/geos/src/operation/valid/IsValidOp.cpp \
    core/geos/src/operation/valid/QuadtreeNestedRingTester.cpp \
    core/geos/src/operation/valid/RepeatedPointTester.cpp \
    core/geos/src/operation/valid/SimpleNestedRingTester.cpp \
    core/geos/src/operation/valid/SweeplineNestedRingTester.cpp \
    core/geos/src/operation/valid/TopologyValidationError.cpp \
    core/geos/src/operation/GeometryGraphOperation.cpp \
    core/geos/src/operation/IsSimpleOp.cpp \
    core/geos/src/planargraph/algorithm/ConnectedSubgraphFinder.cpp \
    core/geos/src/planargraph/DirectedEdgePlanarGraph.cpp \
    core/geos/src/planargraph/DirectedEdgeStarPlanarGraph.cpp \
    core/geos/src/planargraph/EdgePlanarGraph.cpp \
    core/geos/src/planargraph/NodeMapPlanarGraph.cpp \
    core/geos/src/planargraph/NodePlanarGraph.cpp \
    core/geos/src/planargraph/PlanarGraph.cpp \
    core/geos/src/planargraph/Subgraph.cpp \
    core/geos/src/precision/CommonBits.cpp \
    core/geos/src/precision/CommonBitsOp.cpp \
    core/geos/src/precision/CommonBitsRemover.cpp \
    core/geos/src/precision/EnhancedPrecisionOp.cpp \
    core/geos/src/precision/GeometryPrecisionReducer.cpp \
    core/geos/src/precision/PrecisionReducerCoordinateOperation.cpp \
    core/geos/src/precision/SimpleGeometryPrecisionReducer.cpp \
    core/geos/src/simplify/DouglasPeuckerLineSimplifier.cpp \
    core/geos/src/simplify/DouglasPeuckerSimplifier.cpp \
    core/geos/src/simplify/LineSegmentIndex.cpp \
    core/geos/src/simplify/TaggedLineSegment.cpp \
    core/geos/src/simplify/TaggedLinesSimplifier.cpp \
    core/geos/src/simplify/TaggedLineString.cpp \
    core/geos/src/simplify/TaggedLineStringSimplifier.cpp \
    core/geos/src/simplify/TopologyPreservingSimplifier.cpp \
    core/geos/src/triangulate/quadedge/LastFoundQuadEdgeLocator.cpp \
    core/geos/src/triangulate/quadedge/LocateFailureException.cpp \
    core/geos/src/triangulate/quadedge/QuadEdge.cpp \
    core/geos/src/triangulate/quadedge/QuadEdgeLocator.cpp \
    core/geos/src/triangulate/quadedge/QuadEdgeSubdivision.cpp \
    core/geos/src/triangulate/quadedge/TrianglePredicate.cpp \
    core/geos/src/triangulate/quadedge/TriangleVisitor.cpp \
    core/geos/src/triangulate/quadedge/Vertex.cpp \
    core/geos/src/triangulate/DelaunayTriangulationBuilder.cpp \
    core/geos/src/triangulate/IncrementalDelaunayTriangulator.cpp \
    core/geos/src/triangulate/VoronoiDiagramBuilder.cpp \
    core/geos/src/util/Assert.cpp \
    core/geos/src/util/GeometricShapeFactory.cpp \
    core/geos/src/util/Interrupt.cpp \
    core/geos/src/util/math.cpp \
    core/geos/src/util/Profiler.cpp \
    core/geos/src/inlines.cpp \
    core/util/ilwiscoordinate.cpp \
    core/util/ilwisangle.cpp \
    core/ilwisobjects/operation/modeller/analysispattern.cpp \
    core/ilwisobjects/operation/modeller/model.cpp \
    core/ilwisobjects/operation/modeller/modellerfactory.cpp \
    core/ilwisobjects/operation/modeller/applicationmodel.cpp \
    core/ilwisobjects/operation/modeller/workflownode.cpp \
    core/ilwisobjects/operation/modeller/workflowparameter.cpp \
    core/ilwisobjects/operation/modeller/workflowimplementation.cpp \
    core/ilwisobjects/operation/modeller/junctionNode.cpp \
    core/ilwisobjects/operation/modeller/conditionNode.cpp \
    core/ilwisobjects/operation/modeller/operationnode.cpp \
    core/ilwisobjects/operation/modeller/executionnode.cpp \
    core/ilwisobjects/table/combinationmatrix.cpp \
    core/ilwisobjects/operation/modeller/rangenode.cpp \
    core/ilwisobjects/operation/modeller/rangejunctionnode.cpp

HEADERS += core/kernel.h\
      core/kernel_global.h \
    core/version.h \
    core/module.h \
    core/ilwis.h \
    core/errorobject.h \
    core/factory.h \
    core/abstractfactory.h \
    core/ilwisobjects/ilwisdata.h \
    core/ilwisobjects/ilwisobject.h \
    core/ilwisobjects/geometry/coordinatesystem/coordinatesystem.h \
    core/ilwisobjects/geometry/georeference/georeference.h \
    core/ilwisobjects/geometry/georeference/simpelgeoreference.h \
    core/ilwisobjects/geometry/georeference/cornersgeoreference.h \
    core/ilwisobjects/coverage/coverage.h \
    core/publicdatabase.h \
    core/ilwisobjects/ilwisobjectfactory.h \
    core/issuelogger.h \
    core/identity.h \
    core/ilwisobjects/table/table.h \
    core/ilwisobjects/domain/domain.h \
    core/ilwisobjects/domain/thematicitem.h \
    core/util/range.h \
    core/catalog/catalog.h \
    core/catalog/catalogconnector.h \
    core/connectorfactory.h \
    core/connectorinterface.h \
    core/ilwiscontext.h \
    core/catalog/mastercatalog.h \
    core/catalog/catalogquery.h \
    core/catalog/resource.h \
    core/ilwisobjects/ilwisobjectconnector.h \
    core/ilwisobjects/geometry/coordinatesystem/conventionalcoordinatesystem.h \
    core/util/juliantime.h \
    core/ilwisobjects/domain/numericdomain.h \
    core/ilwisobjects/domain/itemdomain.h \
    core/ilwisobjects/domain/identifierrange.h \
    core/ilwisobjects/domain/identifieritem.h \
    core/ilwisobjects/domain/domainitem.h \
    core/util/memorymanager.h \
    core/ilwisobjects/domain/itemrange.h \
    core/ilwisobjects/coverage/blockiterator.h \
    core/util/box.h \
    core/ilwisobjects/coverage/pixeliterator.h \
    core/ilwisobjects/coverage/feature.h \
    core/ilwisobjects/coverage/featurecoverage.h \
    core/util/containerstatistics.h \
    core/ilwisobjects/coverage/grid.h \
    core/util/size.h \
    core/ilwisobjects/table/flattable.h \
    core/ilwisobjects/table/columndefinition.h \
    core/ilwisobjects/coverage/featureiterator.h \
    core/ilwisobjects/table/basetable.h \
    core/ilwisobjects/coverage/featurefactory.h \
    core/util/errmessages.h \
    core/ilwisobjects/geometry/coordinatesystem/projectionimplementation.h \
    core/ilwisobjects/geometry/coordinatesystem/projectionfactory.h \
    core/ilwisobjects/geometry/coordinatesystem/projection.h \
    core/ilwisobjects/geometry/coordinatesystem/proj4parameters.h \
    core/ilwisobjects/geometry/coordinatesystem/ellipsoid.h \
    core/ilwisobjects/geometry/coordinatesystem/geodeticdatum.h \
    core/ilwisobjects/operation/operation.h \
    core/ilwisobjects/operation/operationmetadata.h \
    core/ilwisobjects/operation/operationExpression.h \
    core/ilwisobjects/operation/operationconnector.h \
    core/ilwisobjects/operation/commandhandler.h \
    core/util/locker.h \
    core/ilwisobjects/coverage/raster.h \
    core/ilwisobjects/operation/ilwisoperation.h \
    core/ilwisobjects/domain/datadefinition.h \
    core/util/geometries.h \
    core/ilwisobjects/geometry/georeference/ctpgeoreference.h \
    core/ilwisobjects/geometry/georeference/controlpoint.h \
    core/ilwisobjects/geometry/georeference/planarctpgeoreference.h \
    core/util/mathhelper.h \
    core/ilwisobjects/domain/textdomain.h \
    core/ilwisobjects/geometry/georeference/georefadapter.h \
    core/ilwisobjects/operation/symboltable.h \
    core/ilwisobjects/operation/operationhelpergrid.h \
    core/ilwisobjects/operation/operationhelper.h \
    core/ilwisobjects/operation/operationhelperfeatures.h \
    core/ilwisobjects/geometry/georeference/georefimplementation.h \
    core/ilwisobjects/geometry/georeference/georefimplementationfactory.h \
    core/ilwisobjects/domain/coordinatedomain.h \
    core/ilwisobjects/coverage/indexslicer.h \
    core/ilwisobjects/coverage/rastercoverage.h \
    core/ilwisobjects/coverage/rasterinterpolator.h \
    core/ilwisobjects/domain/itemiterator.h \
    core/ilwisobjects/operation/logicalexpressionparser.h \
    core/ilwisobjects/table/tableselector.h \
    core/ilwisobjects/table/tablemerger.h \
    core/ilwisobjects/domain/domainmerger.h \
    core/util/tranquilizer.h \
    core/ilwisobjects/operation/numericoperation.h \
    core/util/location.h \
    core/ilwisobjects/geometry/coordinatesystem/csytransform.h \
    core/ilwisobjects/coverage/geometryhelper.h \
    core/ilwisobjects/operation/rasterfilter.h \
    core/catalog/dataformat.h \
    core/ilwisobjects/domain/domainhelper.h \
    core/ilwisobjects/domain/numericrange.h \
    core/ilwisobjects/domain/colordomain.h \
    core/ilwisobjects/domain/colorrange.h \
    core/catalog/catalogexplorer.h \
    core/catalog/foldercatalogexplorer.h \
    core/iooptions.h \
    core/catalog/catalogview.h \
    core/ilwisobjects/coverage/vertexiterator.h \
    core/ilwisobjects/domain/coloritem.h \
    core/ilwistypes.h \
    core/oshelper.h \
    core/ilwisobjects/operation/operationoverloads.h \
    core/ilwisobjects/operation/classification/featurespace.h \
    core/ilwisobjects/operation/classification/sampleset.h \
    core/ilwisobjects/operation/classification/samplestatistics.h \
    core/ilwisobjects/domain/interval.h \
    core/ilwisobjects/domain/intervalrange.h \
    core/ilwisobjects/geometry/coordinatesystem/projectionimplementation.h \
    core/kernel_global.h \
    core/ilwisobjects/geometry/georeference/undeterminedgeoreference.h \
    core/ilwisobjects/geometry/coordinatesystem/boundsonlycoordinatesystem.h \
    core/ilwisobjects/domain/rangeiterator.h \
    core/catalog/dataset.h \
    core/util/bresenham.h \
    core/util/xpathparser.h \
    core/util/xmlstreamparser.h \
    core/util/ilwisconfiguration.h \
    core/util/supportlibraryloader.h \
    core/iooptions.h \
    core/ilwisobjects/operation/operationspec.h \
    core/ilwisobjects/table/record.h \
    core/ilwisobjects/table/attributedefinition.h \
    core/ilwisinterfaces.h \
    core/ilwisobjects/table/attributetable.h \
    core/ilwisobjects/table/selectabletable.h \
    core/ilwisobjects/representation/representation.h \
    core/ilwisobjects/representation/colorlookup.h \
    core/ilwisobjects/representation/continuouscolorlookup.h \
    core/ilwisobjects/representation/palettecolorlookup.h \
    core/kernel_global.h \
    core/ilwisobjects/operation/modeller/workflow.h \
    core/util/tranquilizerfactory.h \
    core/util/consoletranquilizer.h \
    core/ilwisobjects/representation/shapelookup.h \
    core/identityinterface.h \
    core/internaldatabaseconnection.h \
    core/catalog/mastercatalogcache.h \
    core/catalog/catalogexplorerworker.h \
    core/ilwisobjects/operation/script.h \
    core/geos/include/geos/algorithm/distance/DiscreteHausdorffDistance.h \
    core/geos/include/geos/algorithm/distance/DistanceToPoint.h \
    core/geos/include/geos/algorithm/distance/PointPairDistance.h \
    core/geos/include/geos/algorithm/locate/IndexedPointInAreaLocator.h \
    core/geos/include/geos/algorithm/locate/PointOnGeometryLocator.h \
    core/geos/include/geos/algorithm/locate/SimplePointInAreaLocator.h \
    core/geos/include/geos/algorithm/Angle.h \
    core/geos/include/geos/algorithm/BoundaryNodeRule.h \
    core/geos/include/geos/algorithm/CentralEndpointIntersector.h \
    core/geos/include/geos/algorithm/Centroid.h \
    core/geos/include/geos/algorithm/CentroidArea.h \
    core/geos/include/geos/algorithm/CentroidLine.h \
    core/geos/include/geos/algorithm/CentroidPoint.h \
    core/geos/include/geos/algorithm/CGAlgorithms.h \
    core/geos/include/geos/algorithm/ConvexHull.h \
    core/geos/include/geos/algorithm/HCoordinate.h \
    core/geos/include/geos/algorithm/InteriorPointArea.h \
    core/geos/include/geos/algorithm/InteriorPointLine.h \
    core/geos/include/geos/algorithm/InteriorPointPoint.h \
    core/geos/include/geos/algorithm/LineIntersector.h \
    core/geos/include/geos/algorithm/MCPointInRing.h \
    core/geos/include/geos/algorithm/MinimumDiameter.h \
    core/geos/include/geos/algorithm/NotRepresentableException.h \
    core/geos/include/geos/algorithm/PointInRing.h \
    core/geos/include/geos/algorithm/PointLocator.h \
    core/geos/include/geos/algorithm/RayCrossingCounter.h \
    core/geos/include/geos/algorithm/RobustDeterminant.h \
    core/geos/include/geos/algorithm/SimplePointInRing.h \
    core/geos/include/geos/algorithm/SIRtreePointInRing.h \
    core/geos/include/geos/geom/prep/AbstractPreparedPolygonContains.h \
    core/geos/include/geos/geom/prep/BasicPreparedGeometry.h \
    core/geos/include/geos/geom/prep/PreparedGeometry.h \
    core/geos/include/geos/geom/prep/PreparedGeometryFactory.h \
    core/geos/include/geos/geom/prep/PreparedLineString.h \
    core/geos/include/geos/geom/prep/PreparedLineStringIntersects.h \
    core/geos/include/geos/geom/prep/PreparedPoint.h \
    core/geos/include/geos/geom/prep/PreparedPolygon.h \
    core/geos/include/geos/geom/prep/PreparedPolygonContains.h \
    core/geos/include/geos/geom/prep/PreparedPolygonContainsProperly.h \
    core/geos/include/geos/geom/prep/PreparedPolygonCovers.h \
    core/geos/include/geos/geom/prep/PreparedPolygonIntersects.h \
    core/geos/include/geos/geom/prep/PreparedPolygonPredicate.h \
    core/geos/include/geos/geom/util/ComponentCoordinateExtracter.h \
    core/geos/include/geos/geom/util/CoordinateOperation.h \
    core/geos/include/geos/geom/util/GeometryCombiner.h \
    core/geos/include/geos/geom/util/GeometryEditor.h \
    core/geos/include/geos/geom/util/GeometryEditorOperation.h \
    core/geos/include/geos/geom/util/GeometryExtracter.h \
    core/geos/include/geos/geom/util/GeometryTransformer.h \
    core/geos/include/geos/geom/util/LinearComponentExtracter.h \
    core/geos/include/geos/geom/util/PointExtracter.h \
    core/geos/include/geos/geom/util/PolygonExtracter.h \
    core/geos/include/geos/geom/util/ShortCircuitedGeometryVisitor.h \
    core/geos/include/geos/geom/util/SineStarFactory.h \
    core/geos/include/geos/geom/BinaryOp.h \
    core/geos/include/geos/geom/Coordinate.h \
    core/geos/include/geos/geom/CoordinateArraySequence.h \
    core/geos/include/geos/geom/CoordinateArraySequenceFactory.h \
    core/geos/include/geos/geom/CoordinateFilter.h \
    core/geos/include/geos/geom/CoordinateList.h \
    core/geos/include/geos/geom/CoordinateSequence.h \
    core/geos/include/geos/geom/CoordinateSequenceFactory.h \
    core/geos/include/geos/geom/CoordinateSequenceFilter.h \
    core/geos/include/geos/geom/Dimension.h \
    core/geos/include/geos/geom/Envelope.h \
    core/geos/include/geos/geom/Geometry.h \
    core/geos/include/geos/geom/GeometryCollection.h \
    core/geos/include/geos/geom/GeometryComponentFilter.h \
    core/geos/include/geos/geom/GeometryFactory.h \
    core/geos/include/geos/geom/GeometryFilter.h \
    core/geos/include/geos/geom/GeometryList.h \
    core/geos/include/geos/geom/IntersectionMatrix.h \
    core/geos/include/geos/geom/Lineal.h \
    core/geos/include/geos/geom/LinearRing.h \
    core/geos/include/geos/geom/LineSegment.h \
    core/geos/include/geos/geom/LineString.h \
    core/geos/include/geos/geom/Location.h \
    core/geos/include/geos/geom/MultiLineString.h \
    core/geos/include/geos/geom/MultiPoint.h \
    core/geos/include/geos/geom/MultiPolygon.h \
    core/geos/include/geos/geom/Point.h \
    core/geos/include/geos/geom/Polygon.h \
    core/geos/include/geos/geom/Polygonal.h \
    core/geos/include/geos/geom/PrecisionModel.h \
    core/geos/include/geos/geom/Puntal.h \
    core/geos/include/geos/geom/Triangle.h \
    core/geos/include/geos/geomgraph/index/EdgeSetIntersector.h \
    core/geos/include/geos/geomgraph/index/MonotoneChain.h \
    core/geos/include/geos/geomgraph/index/MonotoneChainEdge.h \
    core/geos/include/geos/geomgraph/index/MonotoneChainIndexer.h \
    core/geos/include/geos/geomgraph/index/SegmentIntersector.h \
    core/geos/include/geos/geomgraph/index/SimpleEdgeSetIntersector.h \
    core/geos/include/geos/geomgraph/index/SimpleMCSweepLineIntersector.h \
    core/geos/include/geos/geomgraph/index/SimpleSweepLineIntersector.h \
    core/geos/include/geos/geomgraph/index/SweepLineEvent.h \
    core/geos/include/geos/geomgraph/index/SweepLineEventObj.h \
    core/geos/include/geos/geomgraph/index/SweepLineSegment.h \
    core/geos/include/geos/geomgraph/Depth.h \
    core/geos/include/geos/geomgraph/DirectedEdge.h \
    core/geos/include/geos/geomgraph/DirectedEdgeStar.h \
    core/geos/include/geos/geomgraph/Edge.h \
    core/geos/include/geos/geomgraph/EdgeEnd.h \
    core/geos/include/geos/geomgraph/EdgeEndStar.h \
    core/geos/include/geos/geomgraph/EdgeIntersection.h \
    core/geos/include/geos/geomgraph/EdgeIntersectionList.h \
    core/geos/include/geos/geomgraph/EdgeList.h \
    core/geos/include/geos/geomgraph/EdgeNodingValidator.h \
    core/geos/include/geos/geomgraph/EdgeRing.h \
    core/geos/include/geos/geomgraph/GeometryGraph.h \
    core/geos/include/geos/geomgraph/GraphComponent.h \
    core/geos/include/geos/geomgraph/Label.h \
    core/geos/include/geos/geomgraph/Node.h \
    core/geos/include/geos/geomgraph/NodeFactory.h \
    core/geos/include/geos/geomgraph/NodeMap.h \
    core/geos/include/geos/geomgraph/PlanarGraph.h \
    core/geos/include/geos/geomgraph/Position.h \
    core/geos/include/geos/geomgraph/Quadrant.h \
    core/geos/include/geos/geomgraph/TopologyLocation.h \
    core/geos/include/geos/index/bintree/Bintree.h \
    core/geos/include/geos/index/bintree/Interval.h \
    core/geos/include/geos/index/bintree/Key.h \
    core/geos/include/geos/index/bintree/Node.h \
    core/geos/include/geos/index/bintree/NodeBase.h \
    core/geos/include/geos/index/bintree/Root.h \
    core/geos/include/geos/index/chain/MonotoneChain.h \
    core/geos/include/geos/index/chain/MonotoneChainBuilder.h \
    core/geos/include/geos/index/chain/MonotoneChainOverlapAction.h \
    core/geos/include/geos/index/chain/MonotoneChainSelectAction.h \
    core/geos/include/geos/index/intervalrtree/IntervalRTreeBranchNode.h \
    core/geos/include/geos/index/intervalrtree/IntervalRTreeLeafNode.h \
    core/geos/include/geos/index/intervalrtree/IntervalRTreeNode.h \
    core/geos/include/geos/index/intervalrtree/SortedPackedIntervalRTree.h \
    core/geos/include/geos/index/quadtree/DoubleBits.h \
    core/geos/include/geos/index/quadtree/IntervalSize.h \
    core/geos/include/geos/index/quadtree/Key.h \
    core/geos/include/geos/index/quadtree/Node.h \
    core/geos/include/geos/index/quadtree/NodeBase.h \
    core/geos/include/geos/index/quadtree/Quadtree.h \
    core/geos/include/geos/index/quadtree/Root.h \
    core/geos/include/geos/index/strtree/AbstractNode.h \
    core/geos/include/geos/index/strtree/AbstractSTRtree.h \
    core/geos/include/geos/index/strtree/Boundable.h \
    core/geos/include/geos/index/strtree/Interval.h \
    core/geos/include/geos/index/strtree/ItemBoundable.h \
    core/geos/include/geos/index/strtree/SIRtree.h \
    core/geos/include/geos/index/strtree/STRtree.h \
    core/geos/include/geos/index/sweepline/SweepLineEvent.h \
    core/geos/include/geos/index/sweepline/SweepLineIndex.h \
    core/geos/include/geos/index/sweepline/SweepLineInterval.h \
    core/geos/include/geos/index/sweepline/SweepLineOverlapAction.h \
    core/geos/include/geos/index/ItemVisitor.h \
    core/geos/include/geos/index/SpatialIndex.h \
    core/geos/include/geos/io/ByteOrderDataInStream.h \
    core/geos/include/geos/io/ByteOrderValues.h \
    core/geos/include/geos/io/CLocalizer.h \
    core/geos/include/geos/io/ParseException.h \
    core/geos/include/geos/io/StringTokenizer.h \
    core/geos/include/geos/io/WKBConstants.h \
    core/geos/include/geos/io/WKBReader.h \
    core/geos/include/geos/io/WKBWriter.h \
    core/geos/include/geos/io/WKTReader.h \
    core/geos/include/geos/io/WKTWriter.h \
    core/geos/include/geos/io/Writer.h \
    core/geos/include/geos/linearref/ExtractLineByLocation.h \
    core/geos/include/geos/linearref/LengthIndexedLine.h \
    core/geos/include/geos/linearref/LengthIndexOfPoint.h \
    core/geos/include/geos/linearref/LengthLocationMap.h \
    core/geos/include/geos/linearref/LinearGeometryBuilder.h \
    core/geos/include/geos/linearref/LinearIterator.h \
    core/geos/include/geos/linearref/LinearLocation.h \
    core/geos/include/geos/linearref/LocationIndexedLine.h \
    core/geos/include/geos/linearref/LocationIndexOfLine.h \
    core/geos/include/geos/linearref/LocationIndexOfPoint.h \
    core/geos/include/geos/noding/snapround/HotPixel.h \
    core/geos/include/geos/noding/snapround/MCIndexPointSnapper.h \
    core/geos/include/geos/noding/snapround/MCIndexSnapRounder.h \
    core/geos/include/geos/noding/snapround/SimpleSnapRounder.h \
    core/geos/include/geos/noding/BasicSegmentString.h \
    core/geos/include/geos/noding/FastNodingValidator.h \
    core/geos/include/geos/noding/FastSegmentSetIntersectionFinder.h \
    core/geos/include/geos/noding/GeometryNoder.h \
    core/geos/include/geos/noding/IntersectionAdder.h \
    core/geos/include/geos/noding/IntersectionFinderAdder.h \
    core/geos/include/geos/noding/IteratedNoder.h \
    core/geos/include/geos/noding/MCIndexNoder.h \
    core/geos/include/geos/noding/MCIndexSegmentSetMutualIntersector.h \
    core/geos/include/geos/noding/NodableSegmentString.h \
    core/geos/include/geos/noding/NodedSegmentString.h \
    core/geos/include/geos/noding/Noder.h \
    core/geos/include/geos/noding/NodingValidator.h \
    core/geos/include/geos/noding/Octant.h \
    core/geos/include/geos/noding/OrientedCoordinateArray.h \
    core/geos/include/geos/noding/ScaledNoder.h \
    core/geos/include/geos/noding/SegmentIntersectionDetector.h \
    core/geos/include/geos/noding/SegmentIntersector.h \
    core/geos/include/geos/noding/SegmentNode.h \
    core/geos/include/geos/noding/SegmentNodeList.h \
    core/geos/include/geos/noding/SegmentPointComparator.h \
    core/geos/include/geos/noding/SegmentSetMutualIntersector.h \
    core/geos/include/geos/noding/SegmentString.h \
    core/geos/include/geos/noding/SegmentStringUtil.h \
    core/geos/include/geos/noding/SimpleNoder.h \
    core/geos/include/geos/noding/SingleInteriorIntersectionFinder.h \
    core/geos/include/geos/noding/SinglePassNoder.h \
    core/geos/include/geos/operation/buffer/BufferBuilder.h \
    core/geos/include/geos/operation/buffer/BufferInputLineSimplifier.h \
    core/geos/include/geos/operation/buffer/BufferOp.h \
    core/geos/include/geos/operation/buffer/BufferParameters.h \
    core/geos/include/geos/operation/buffer/BufferSubgraph.h \
    core/geos/include/geos/operation/buffer/OffsetCurveBuilder.h \
    core/geos/include/geos/operation/buffer/OffsetCurveSetBuilder.h \
    core/geos/include/geos/operation/buffer/OffsetSegmentGenerator.h \
    core/geos/include/geos/operation/buffer/OffsetSegmentString.h \
    core/geos/include/geos/operation/buffer/RightmostEdgeFinder.h \
    core/geos/include/geos/operation/buffer/SubgraphDepthLocater.h \
    core/geos/include/geos/operation/distance/ConnectedElementLocationFilter.h \
    core/geos/include/geos/operation/distance/ConnectedElementPointFilter.h \
    core/geos/include/geos/operation/distance/DistanceOp.h \
    core/geos/include/geos/operation/distance/GeometryLocation.h \
    core/geos/include/geos/operation/intersection/Rectangle.h \
    core/geos/include/geos/operation/intersection/RectangleIntersection.h \
    core/geos/include/geos/operation/intersection/RectangleIntersectionBuilder.h \
    core/geos/include/geos/operation/linemerge/EdgeString.h \
    core/geos/include/geos/operation/linemerge/LineMergeDirectedEdge.h \
    core/geos/include/geos/operation/linemerge/LineMergeEdge.h \
    core/geos/include/geos/operation/linemerge/LineMergeGraph.h \
    core/geos/include/geos/operation/linemerge/LineMerger.h \
    core/geos/include/geos/operation/linemerge/LineSequencer.h \
    core/geos/include/geos/operation/overlay/snap/GeometrySnapper.h \
    core/geos/include/geos/operation/overlay/snap/LineStringSnapper.h \
    core/geos/include/geos/operation/overlay/snap/SnapIfNeededOverlayOp.h \
    core/geos/include/geos/operation/overlay/snap/SnapOverlayOp.h \
    core/geos/include/geos/operation/overlay/validate/FuzzyPointLocator.h \
    core/geos/include/geos/operation/overlay/validate/OffsetPointGenerator.h \
    core/geos/include/geos/operation/overlay/validate/OverlayResultValidator.h \
    core/geos/include/geos/operation/overlay/EdgeSetNoder.h \
    core/geos/include/geos/operation/overlay/ElevationMatrix.h \
    core/geos/include/geos/operation/overlay/ElevationMatrixCell.h \
    core/geos/include/geos/operation/overlay/LineBuilder.h \
    core/geos/include/geos/operation/overlay/MaximalEdgeRing.h \
    core/geos/include/geos/operation/overlay/MinimalEdgeRing.h \
    core/geos/include/geos/operation/overlay/OverlayNodeFactory.h \
    core/geos/include/geos/operation/overlay/OverlayOp.h \
    core/geos/include/geos/operation/overlay/PointBuilder.h \
    core/geos/include/geos/operation/overlay/PolygonBuilder.h \
    core/geos/include/geos/operation/polygonize/EdgeRing.h \
    core/geos/include/geos/operation/polygonize/PolygonizeDirectedEdge.h \
    core/geos/include/geos/operation/polygonize/PolygonizeEdge.h \
    core/geos/include/geos/operation/polygonize/PolygonizeGraph.h \
    core/geos/include/geos/operation/polygonize/Polygonizer.h \
    core/geos/include/geos/operation/predicate/RectangleContains.h \
    core/geos/include/geos/operation/predicate/RectangleIntersects.h \
    core/geos/include/geos/operation/predicate/SegmentIntersectionTester.h \
    core/geos/include/geos/operation/relate/EdgeEndBuilder.h \
    core/geos/include/geos/operation/relate/EdgeEndBundle.h \
    core/geos/include/geos/operation/relate/EdgeEndBundleStar.h \
    core/geos/include/geos/operation/relate/RelateComputer.h \
    core/geos/include/geos/operation/relate/RelateNode.h \
    core/geos/include/geos/operation/relate/RelateNodeFactory.h \
    core/geos/include/geos/operation/relate/RelateNodeGraph.h \
    core/geos/include/geos/operation/relate/RelateOp.h \
    core/geos/include/geos/operation/sharedpaths/SharedPathsOp.h \
    core/geos/include/geos/operation/union/CascadedPolygonUnion.h \
    core/geos/include/geos/operation/union/CascadedUnion.h \
    core/geos/include/geos/operation/union/GeometryListHolder.h \
    core/geos/include/geos/operation/union/PointGeometryUnion.h \
    core/geos/include/geos/operation/union/UnaryUnionOp.h \
    core/geos/include/geos/operation/valid/ConnectedInteriorTester.h \
    core/geos/include/geos/operation/valid/ConsistentAreaTester.h \
    core/geos/include/geos/operation/valid/IsValidOp.h \
    core/geos/include/geos/operation/valid/QuadtreeNestedRingTester.h \
    core/geos/include/geos/operation/valid/RepeatedPointTester.h \
    core/geos/include/geos/operation/valid/SimpleNestedRingTester.h \
    core/geos/include/geos/operation/valid/SweeplineNestedRingTester.h \
    core/geos/include/geos/operation/valid/TopologyValidationError.h \
    core/geos/include/geos/operation/GeometryGraphOperation.h \
    core/geos/include/geos/operation/IsSimpleOp.h \
    core/geos/include/geos/planargraph/algorithm/ConnectedSubgraphFinder.h \
    core/geos/include/geos/planargraph/DirectedEdge.h \
    core/geos/include/geos/planargraph/DirectedEdgeStar.h \
    core/geos/include/geos/planargraph/Edge.h \
    core/geos/include/geos/planargraph/GraphComponent.h \
    core/geos/include/geos/planargraph/Node.h \
    core/geos/include/geos/planargraph/NodeMap.h \
    core/geos/include/geos/planargraph/PlanarGraph.h \
    core/geos/include/geos/planargraph/Subgraph.h \
    core/geos/include/geos/precision/CommonBits.h \
    core/geos/include/geos/precision/CommonBitsOp.h \
    core/geos/include/geos/precision/CommonBitsRemover.h \
    core/geos/include/geos/precision/EnhancedPrecisionOp.h \
    core/geos/include/geos/precision/GeometryPrecisionReducer.h \
    core/geos/include/geos/precision/PrecisionReducerCoordinateOperation.h \
    core/geos/include/geos/precision/SimpleGeometryPrecisionReducer.h \
    core/geos/include/geos/simplify/DouglasPeuckerLineSimplifier.h \
    core/geos/include/geos/simplify/DouglasPeuckerSimplifier.h \
    core/geos/include/geos/simplify/LineSegmentIndex.h \
    core/geos/include/geos/simplify/TaggedLineSegment.h \
    core/geos/include/geos/simplify/TaggedLinesSimplifier.h \
    core/geos/include/geos/simplify/TaggedLineString.h \
    core/geos/include/geos/simplify/TaggedLineStringSimplifier.h \
    core/geos/include/geos/simplify/TopologyPreservingSimplifier.h \
    core/geos/include/geos/triangulate/quadedge/LastFoundQuadEdgeLocator.h \
    core/geos/include/geos/triangulate/quadedge/LocateFailureException.h \
    core/geos/include/geos/triangulate/quadedge/QuadEdge.h \
    core/geos/include/geos/triangulate/quadedge/QuadEdgeLocator.h \
    core/geos/include/geos/triangulate/quadedge/QuadEdgeSubdivision.h \
    core/geos/include/geos/triangulate/quadedge/TrianglePredicate.h \
    core/geos/include/geos/triangulate/quadedge/TriangleVisitor.h \
    core/geos/include/geos/triangulate/quadedge/Vertex.h \
    core/geos/include/geos/triangulate/DelaunayTriangulationBuilder.h \
    core/geos/include/geos/triangulate/IncrementalDelaunayTriangulator.h \
    core/geos/include/geos/triangulate/VoronoiDiagramBuilder.h \
    core/geos/include/geos/util/Assert.h \
    core/geos/include/geos/util/AssertionFailedException.h \
    core/geos/include/geos/util/CoordinateArrayFilter.h \
    core/geos/include/geos/util/GeometricShapeFactory.h \
    core/geos/include/geos/util/GEOSException.h \
    core/geos/include/geos/util/IllegalArgumentException.h \
    core/geos/include/geos/util/IllegalStateException.h \
    core/geos/include/geos/util/Interrupt.h \
    core/geos/include/geos/util/Machine.h \
    core/geos/include/geos/util/math.h \
    core/geos/include/geos/util/TopologyException.h \
    core/geos/include/geos/util/UniqueCoordinateArrayFilter.h \
    core/geos/include/geos/util/UnsupportedOperationException.h \
    core/geos/include/geos/export.h \
    core/geos/include/geos/geom.h \
    core/geos/include/geos/geomgraph.h \
    core/geos/include/geos/geomgraphindex.h \
    core/geos/include/geos/geomUtil.h \
    core/geos/include/geos/geosAlgorithm.h \
    core/geos/include/geos/indexBintree.h \
    core/geos/include/geos/indexChain.h \
    core/geos/include/geos/indexQuadtree.h \
    core/geos/include/geos/indexStrtree.h \
    core/geos/include/geos/indexSweepline.h \
    core/geos/include/geos/inline.h \
    core/geos/include/geos/io.h \
    core/geos/include/geos/noding.h \
    core/geos/include/geos/nodingSnapround.h \
    core/geos/include/geos/opBuffer.h \
    core/geos/include/geos/opDistance.h \
    core/geos/include/geos/operation.h \
    core/geos/include/geos/opLinemerge.h \
    core/geos/include/geos/opOverlay.h \
    core/geos/include/geos/opPolygonize.h \
    core/geos/include/geos/opPredicate.h \
    core/geos/include/geos/opRelate.h \
    core/geos/include/geos/opValid.h \
    core/geos/include/geos/planargraph.h \
    core/geos/include/geos/platform.h \
    core/geos/include/geos/platform.h.in \
    core/geos/include/geos/platform.h.vc \
    core/geos/include/geos/precision.h \
    core/geos/include/geos/profiler.h \
    core/geos/include/geos/spatialIndex.h \
    core/geos/include/geos/timeval.h \
    core/geos/include/geos/unload.h \
    core/geos/include/geos/util.h \
    core/geos/include/geos/version.h \
    core/geos/include/geos/version.h.in \
    core/geos/include/geos/version.h.vc \
    core/geos/include/geos.h \
    core/geos/src/operation/valid/IndexedNestedRingTester.h \
    core/util/ilwiscoordinate.h \
    core/util/ilwisangle.h \
    core/ilwisobjects/operation/modeller/analysispattern.h \
    core/ilwisobjects/operation/modeller/model.h \
    core/ilwisobjects/operation/modeller/modellerfactory.h \
    core/ilwisobjects/operation/modeller/applicationmodel.h \
    core/ilwisobjects/operation/modeller/workflowparameter.h \
    core/ilwisobjects/operation/modeller/workflownode.h \
    core/ilwisobjects/operation/modeller/workflowimplementation.h \
    core/ilwisobjects/operation/modeller/conditionNode.h \
    core/ilwisobjects/operation/modeller/junctionNode.h \
    core/ilwisobjects/operation/modeller/operationnode.h \
    core/ilwisobjects/operation/modeller/executionnode.h \
    core/ilwisobjects/table/combinationmatrix.h \
    core/ilwisobjects/operation/modeller/rangenode.h \
    core/ilwisobjects/operation/modeller/rangejunctionnode.h

OTHER_FILES += \
    core/resources/referencesystems.csv \
    core/resources/projections.csv \
    core/resources/numericdomains.csv \
    core/resources/filters.csv \
    core/resources/epsg.pcs \
    core/resources/ellipsoids.csv \
    core/resources/datums.csv \
    core/resources/representations.csv \
    core/resources/featurefragmentshader_nvdia.glsl \
    core/resources/featurevertexshader_nvdia.glsl \
    core/resources/rasterfragmentshader_nvdia.glsl \
    core/resources/rastervertexshader_nvdia.glsl \
    LICENSE-2.0.txt \
    installer.nsi \
    core/resources/ilwis.config \
    core/resources/country_boundaries.ilwis\
    core/resources/color_chart.csv



win32{
    CONFIG(debug, debug|release) {
        qtdlls.files = "$$[QT_INSTALL_PREFIX]/bin/Qt5Cored.dll" \
                       "$$[QT_INSTALL_PREFIX]/bin/Qt5Sqld.dll" \
                       "$$[QT_INSTALL_PREFIX]/bin/Qt5Guid.dll" \
                       "$$[QT_INSTALL_PREFIX]/bin/Qt5XmlPatternsd.dll" \
                       "$$[QT_INSTALL_PREFIX]/bin/Qt5Networkd.dll"
    }else{
        qtdlls.files = "$$[QT_INSTALL_PREFIX]/bin/Qt5Core.dll" \
                       "$$[QT_INSTALL_PREFIX]/bin/Qt5Sql.dll" \
                       "$$[QT_INSTALL_PREFIX]/bin/Qt5Gui.dll" \
                       "$$[QT_INSTALL_PREFIX]/bin/Qt5XmlPatterns.dll" \
                       "$$[QT_INSTALL_PREFIX]/bin/Qt5Network.dll"
    }
    qtdlls.files +=   "$$[QT_INSTALL_PREFIX]/bin/libgcc_s_dw2-1.dll" \
                      "$$[QT_INSTALL_PREFIX]/bin/libstdc++-6.dll" \
                      "$$[QT_INSTALL_PREFIX]/bin/libwinpthread-1.dll" \
                      "$$[QT_INSTALL_PREFIX]/bin/icudt51.dll" \
                      "$$[QT_INSTALL_PREFIX]/bin/icuin51.dll" \
                      "$$[QT_INSTALL_PREFIX]/bin/icuuc51.dll"
    qtdlls.path = $$PWD/../output/$$PLATFORM$$CONF/bin

    qtcreatepluginsdir.commands += @echo "exists($$DLLDESTDIR/plugins)" $$escape_expand(\\n\\t)
    !exists($$DLLDESTDIR/plugins) {
        qtcreatepluginsdir.commands += md $$DLLDESTDIR/plugins $$escape_expand(\\n\\t)
        !exists($$DLLDESTDIR/plugins/sqldrivers) {
            qtcreatepluginsdir.commands += md $$DLLDESTDIR/plugins/sqldrivers $$escape_expand(\\n\\t)
        }
    }

    CONFIG(debug, debug|release) {
        qtsqlplugin.files = $$[QT_INSTALL_PREFIX]/plugins/sqldrivers/qsqlited.dll
    }else{
        qtsqlplugin.files = $$[QT_INSTALL_PREFIX]/plugins/sqldrivers/qsqlite.dll
    }
    qtsqlplugin.path = $$PWD/../output/$$PLATFORM$$CONF/bin/plugins/sqldrivers

    INSTALLS += qtdlls qtsqlplugin

    QMAKE_EXTRA_TARGETS = qtcreatepluginsdir

}

DESTDIR = $$PWD/../libraries/$$PLATFORM$$CONF

resources.files = core/resources/referencesystems.csv \
    core/resources/codes_with_latlon_order.csv \
    core/resources/projections.csv \
    core/resources/numericdomains.csv \
    core/resources/filters.csv \
    core/resources/epsg.pcs \
    core/resources/ellipsoids.csv \
    core/resources/datums.csv \
    core/resources/representations.csv \
    core/resources/featurefragmentshader_nvdia.glsl \
    core/resources/featurevertexshader_nvdia.glsl \
    core/resources/rasterfragmentshader_nvdia.glsl \
    core/resources/rastervertexshader_nvdia.glsl \
    core/resources/ilwis.config \
    core/resources/country_boundaries.ilwis \
    core/resources/teritories.csv \
    core/resources/color_chart.csv \
    core/resources/svgcolornames.txt\
    core/resources/extract_epsgCodes_with_forcedXY.py 


win32{
    DLLDESTDIR = $$PWD/../output/$$PLATFORM$$CONF/bin
    resources.path = $$clean_path($$DLLDESTDIR/resources)
}
linux{
    resources.path = $$clean_path($$PWD/../output/$$PLATFORM$$CONF/bin/resources)
    target.path = $$PWD/../output/$$PLATFORM$$CONF/bin
    INSTALLS += target
}

license.files =  LICENSE-2.0.txt
license.path =   $$PWD/../output/$$PLATFORM$$CONF/bin

installer.files =installer.nsi
installer.path = $$PWD/../output/$$PLATFORM$$CONF/bin

INSTALLS += resources license installer

SOURCE_DIR = $$clean_path($$PWD)

linux {
    for(FILE,resources.files){
        QMAKE_POST_LINK += $$quote($(COPY) $$SOURCE_DIR/$$FILE $$resources.path$$escape_expand(\n\t))
    }
}

win32 {
    resources.files = $$replace(resources.files,/,\\)
    resources.path = $$replace(resources.path,/,\\)
    SOURCE_DIR = $$replace(SOURCE_DIR,/,\\)
    for(FILE,resources.files){
        QMAKE_POST_LINK += $$quote($(COPY) $$SOURCE_DIR\\$$FILE $$resources.path$$escape_expand(\n\t))
    }
}

DISTFILES += \
    core/geos/include/geos/._version.h.vc \
    core/geos/include/config.h.in
