var searchData=
[
  ['identity',['Identity',['../class_ilwis_1_1_identity.html',1,'Ilwis']]],
  ['ilwiscontext',['IlwisContext',['../class_ilwis_1_1_ilwis_context.html',1,'Ilwis']]],
  ['ilwisdata',['IlwisData',['../class_ilwis_1_1_ilwis_data.html',1,'Ilwis']]],
  ['ilwisdata_3c_20coordinatesystem_20_3e',['IlwisData&lt; CoordinateSystem &gt;',['../class_ilwis_1_1_ilwis_data.html',1,'Ilwis']]],
  ['ilwisdata_3c_20featurecoverage_20_3e',['IlwisData&lt; FeatureCoverage &gt;',['../class_ilwis_1_1_ilwis_data.html',1,'Ilwis']]],
  ['ilwisdata_3c_20georeference_20_3e',['IlwisData&lt; GeoReference &gt;',['../class_ilwis_1_1_ilwis_data.html',1,'Ilwis']]],
  ['ilwisdata_3c_20ilwis_3a_3adomain_20_3e',['IlwisData&lt; Ilwis::Domain &gt;',['../class_ilwis_1_1_ilwis_data.html',1,'Ilwis']]],
  ['ilwisdata_3c_20ilwis_3a_3aellipsoid_20_3e',['IlwisData&lt; Ilwis::Ellipsoid &gt;',['../class_ilwis_1_1_ilwis_data.html',1,'Ilwis']]],
  ['ilwisdata_3c_20ilwis_3a_3aoperationmetadata_20_3e',['IlwisData&lt; Ilwis::OperationMetaData &gt;',['../class_ilwis_1_1_ilwis_data.html',1,'Ilwis']]],
  ['ilwisdata_3c_20ilwis_3a_3aprojection_20_3e',['IlwisData&lt; Ilwis::Projection &gt;',['../class_ilwis_1_1_ilwis_data.html',1,'Ilwis']]],
  ['ilwisdata_3c_20rastercoverage_20_3e',['IlwisData&lt; RasterCoverage &gt;',['../class_ilwis_1_1_ilwis_data.html',1,'Ilwis']]],
  ['ilwisdata_3c_20table_20_3e',['IlwisData&lt; Table &gt;',['../class_ilwis_1_1_ilwis_data.html',1,'Ilwis']]],
  ['ilwisobject',['IlwisObject',['../class_ilwis_1_1_ilwis_object.html',1,'Ilwis']]],
  ['ilwisobjectconnector',['IlwisObjectConnector',['../class_ilwis_1_1_ilwis_object_connector.html',1,'Ilwis']]],
  ['ilwisobjectfactory',['IlwisObjectFactory',['../class_ilwis_1_1_ilwis_object_factory.html',1,'Ilwis']]],
  ['indexedidentifier',['IndexedIdentifier',['../class_ilwis_1_1_indexed_identifier.html',1,'Ilwis']]],
  ['indexedidentifierrange',['IndexedIdentifierRange',['../class_ilwis_1_1_indexed_identifier_range.html',1,'Ilwis']]],
  ['indexslicer',['IndexSlicer',['../class_ilwis_1_1_index_slicer.html',1,'Ilwis']]],
  ['internalerror',['InternalError',['../class_ilwis_1_1_internal_error.html',1,'Ilwis']]],
  ['issuelogger',['IssueLogger',['../class_ilwis_1_1_issue_logger.html',1,'Ilwis']]],
  ['issueobject',['IssueObject',['../class_ilwis_1_1_issue_object.html',1,'Ilwis']]],
  ['itemdomain',['ItemDomain',['../class_ilwis_1_1_item_domain.html',1,'Ilwis']]],
  ['itemdomainmergerindexeditems',['ItemDomainMergerIndexedItems',['../class_ilwis_1_1_item_domain_merger_indexed_items.html',1,'Ilwis']]],
  ['itemdomainmergernameditems',['ItemDomainMergerNamedItems',['../class_ilwis_1_1_item_domain_merger_named_items.html',1,'Ilwis']]],
  ['itemiterator',['ItemIterator',['../class_ilwis_1_1_item_iterator.html',1,'Ilwis']]],
  ['itemrange',['ItemRange',['../class_ilwis_1_1_item_range.html',1,'Ilwis']]]
];
