#ifndef PROJECTIONIMPLPROJ4_GLOBAL_H
#define PROJECTIONIMPLPROJ4_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PROJECTIONIMPLPROJ4_LIBRARY)
#  define PROJECTIONIMPLPROJ4SHARED_EXPORT Q_DECL_EXPORT
#else
#  define PROJECTIONIMPLPROJ4SHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // PROJECTIONIMPLPROJ4_GLOBAL_H
