/** \file
 *  This C header file was generated by $ANTLR version 3.4
 *
 *     -  From the grammar source file : D:\\Projects\\Ilwis\\Ilwis4\\projects\\IlwisCore\\ilwisscript\\parserlexer\\ilwisscript.g
 *     -                            On : 2017-05-10 08:09:28
 *     -                 for the lexer : ilwisscriptLexerLexer
 *
 * Editing it, at least manually, is not wise.
 *
 * C language generator and runtime by Jim Idle, jimi|hereisanat|idle|dotgoeshere|ws.
 *
 *
 * The lexer 
ilwisscriptLexer

has the callable functions (rules) shown below,
 * which will invoke the code for the associated rule in the source grammar
 * assuming that the input stream is pointing to a token/text stream that could begin
 * this rule.
 *
 * For instance if you call the first (topmost) rule in a parser grammar, you will
 * get the results of a full parse, but calling a rule half way through the grammar will
 * allow you to pass part of a full token stream to the parser, such as for syntax checking
 * in editors and so on.
 *
 * The parser entry points are called indirectly (by function pointer to function) via
 * a parser context typedef pilwisscriptLexer, which is returned from a call to ilwisscriptLexerNew().
 *
 * As this is a generated lexer, it is unlikely you will call it 'manually'. However
 * the methods are provided anyway.
 *
 * The methods in pilwisscriptLexer are  as follows:
 *
 *  - 
 void
      pilwisscriptLexer->T__13(pilwisscriptLexer)
 *  - 
 void
      pilwisscriptLexer->T__14(pilwisscriptLexer)
 *  - 
 void
      pilwisscriptLexer->T__15(pilwisscriptLexer)
 *  - 
 void
      pilwisscriptLexer->T__16(pilwisscriptLexer)
 *  - 
 void
      pilwisscriptLexer->T__17(pilwisscriptLexer)
 *  - 
 void
      pilwisscriptLexer->T__18(pilwisscriptLexer)
 *  - 
 void
      pilwisscriptLexer->T__19(pilwisscriptLexer)
 *  - 
 void
      pilwisscriptLexer->T__20(pilwisscriptLexer)
 *  - 
 void
      pilwisscriptLexer->T__21(pilwisscriptLexer)
 *  - 
 void
      pilwisscriptLexer->T__22(pilwisscriptLexer)
 *  - 
 void
      pilwisscriptLexer->T__23(pilwisscriptLexer)
 *  - 
 void
      pilwisscriptLexer->T__24(pilwisscriptLexer)
 *  - 
 void
      pilwisscriptLexer->T__25(pilwisscriptLexer)
 *  - 
 void
      pilwisscriptLexer->T__26(pilwisscriptLexer)
 *  - 
 void
      pilwisscriptLexer->T__27(pilwisscriptLexer)
 *  - 
 void
      pilwisscriptLexer->T__28(pilwisscriptLexer)
 *  - 
 void
      pilwisscriptLexer->T__29(pilwisscriptLexer)
 *  - 
 void
      pilwisscriptLexer->T__30(pilwisscriptLexer)
 *  - 
 void
      pilwisscriptLexer->T__31(pilwisscriptLexer)
 *  - 
 void
      pilwisscriptLexer->T__32(pilwisscriptLexer)
 *  - 
 void
      pilwisscriptLexer->T__33(pilwisscriptLexer)
 *  - 
 void
      pilwisscriptLexer->T__34(pilwisscriptLexer)
 *  - 
 void
      pilwisscriptLexer->T__35(pilwisscriptLexer)
 *  - 
 void
      pilwisscriptLexer->T__36(pilwisscriptLexer)
 *  - 
 void
      pilwisscriptLexer->T__37(pilwisscriptLexer)
 *  - 
 void
      pilwisscriptLexer->T__38(pilwisscriptLexer)
 *  - 
 void
      pilwisscriptLexer->T__39(pilwisscriptLexer)
 *  - 
 void
      pilwisscriptLexer->T__40(pilwisscriptLexer)
 *  - 
 void
      pilwisscriptLexer->T__41(pilwisscriptLexer)
 *  - 
 void
      pilwisscriptLexer->T__42(pilwisscriptLexer)
 *  - 
 void
      pilwisscriptLexer->T__43(pilwisscriptLexer)
 *  - 
 void
      pilwisscriptLexer->T__44(pilwisscriptLexer)
 *  - 
 void
      pilwisscriptLexer->T__45(pilwisscriptLexer)
 *  - 
 void
      pilwisscriptLexer->T__46(pilwisscriptLexer)
 *  - 
 void
      pilwisscriptLexer->T__47(pilwisscriptLexer)
 *  - 
 void
      pilwisscriptLexer->T__48(pilwisscriptLexer)
 *  - 
 void
      pilwisscriptLexer->T__49(pilwisscriptLexer)
 *  - 
 void
      pilwisscriptLexer->T__50(pilwisscriptLexer)
 *  - 
 void
      pilwisscriptLexer->T__51(pilwisscriptLexer)
 *  - 
 void
      pilwisscriptLexer->T__52(pilwisscriptLexer)
 *  - 
 void
      pilwisscriptLexer->T__53(pilwisscriptLexer)
 *  - 
 void
      pilwisscriptLexer->T__54(pilwisscriptLexer)
 *  - 
 void
      pilwisscriptLexer->T__55(pilwisscriptLexer)
 *  - 
 void
      pilwisscriptLexer->T__56(pilwisscriptLexer)
 *  - 
 void
      pilwisscriptLexer->T__57(pilwisscriptLexer)
 *  - 
 void
      pilwisscriptLexer->T__58(pilwisscriptLexer)
 *  - 
 void
      pilwisscriptLexer->T__59(pilwisscriptLexer)
 *  - 
 void
      pilwisscriptLexer->T__60(pilwisscriptLexer)
 *  - 
 void
      pilwisscriptLexer->T__61(pilwisscriptLexer)
 *  - 
 void
      pilwisscriptLexer->T__62(pilwisscriptLexer)
 *  - 
 void
      pilwisscriptLexer->T__63(pilwisscriptLexer)
 *  - 
 void
      pilwisscriptLexer->T__64(pilwisscriptLexer)
 *  - 
 void
      pilwisscriptLexer->ID(pilwisscriptLexer)
 *  - 
 void
      pilwisscriptLexer->INT(pilwisscriptLexer)
 *  - 
 void
      pilwisscriptLexer->FLOAT(pilwisscriptLexer)
 *  - 
 void
      pilwisscriptLexer->COMMENT(pilwisscriptLexer)
 *  - 
 void
      pilwisscriptLexer->WS(pilwisscriptLexer)
 *  - 
 void
      pilwisscriptLexer->STRING(pilwisscriptLexer)
 *  - 
 void
      pilwisscriptLexer->EXPONENT(pilwisscriptLexer)
 *  - 
 void
      pilwisscriptLexer->ESC_SEQ(pilwisscriptLexer)
 *  - 
 void
      pilwisscriptLexer->EOL(pilwisscriptLexer)
 *  - 
 void
      pilwisscriptLexer->Tokens(pilwisscriptLexer)
 *
 * The return type for any particular rule is of course determined by the source
 * grammar file.
 */
// [The "BSD license"]
// Copyright (c) 2005-2009 Jim Idle, Temporal Wave LLC
// http://www.temporal-wave.com
// http://www.linkedin.com/in/jimidle
//
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
// 1. Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
// 3. The name of the author may not be used to endorse or promote products
//    derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

#ifndef	_ilwisscriptLexer_H
#define _ilwisscriptLexer_H
/* =============================================================================
 * Standard antlr3 C runtime definitions
 */
#include    <antlr3.h>

/* End of standard antlr 3 runtime definitions
 * =============================================================================
 */

#ifdef __cplusplus
extern "C" {
#endif

// Forward declare the context typedef so that we can use it before it is
// properly defined. Delegators and delegates (from import statements) are
// interdependent and their context structures contain pointers to each other
// C only allows such things to be declared if you pre-declare the typedef.
//
typedef struct ilwisscriptLexer_Ctx_struct ilwisscriptLexer, * pilwisscriptLexer;



#ifdef	ANTLR3_WINDOWS
// Disable: Unreferenced parameter,							- Rules with parameters that are not used
//          constant conditional,							- ANTLR realizes that a prediction is always true (synpred usually)
//          initialized but unused variable					- tree rewrite variables declared but not needed
//          Unreferenced local variable						- lexer rule declares but does not always use _type
//          potentially unitialized variable used			- retval always returned from a rule
//			unreferenced local function has been removed	- susually getTokenNames or freeScope, they can go without warnigns
//
// These are only really displayed at warning level /W4 but that is the code ideal I am aiming at
// and the codegen must generate some of these warnings by necessity, apart from 4100, which is
// usually generated when a parser rule is given a parameter that it does not use. Mostly though
// this is a matter of orthogonality hence I disable that one.
//
#pragma warning( disable : 4100 )
#pragma warning( disable : 4101 )
#pragma warning( disable : 4127 )
#pragma warning( disable : 4189 )
#pragma warning( disable : 4505 )
#pragma warning( disable : 4701 )
#endif

/** Context tracking structure for 
ilwisscriptLexer

 */
struct ilwisscriptLexer_Ctx_struct
{
    /** Built in ANTLR3 context tracker contains all the generic elements
     *  required for context tracking.
     */
    pANTLR3_LEXER    pLexer;

     void
     (*mT__13)	(struct ilwisscriptLexer_Ctx_struct * ctx);

     void
     (*mT__14)	(struct ilwisscriptLexer_Ctx_struct * ctx);

     void
     (*mT__15)	(struct ilwisscriptLexer_Ctx_struct * ctx);

     void
     (*mT__16)	(struct ilwisscriptLexer_Ctx_struct * ctx);

     void
     (*mT__17)	(struct ilwisscriptLexer_Ctx_struct * ctx);

     void
     (*mT__18)	(struct ilwisscriptLexer_Ctx_struct * ctx);

     void
     (*mT__19)	(struct ilwisscriptLexer_Ctx_struct * ctx);

     void
     (*mT__20)	(struct ilwisscriptLexer_Ctx_struct * ctx);

     void
     (*mT__21)	(struct ilwisscriptLexer_Ctx_struct * ctx);

     void
     (*mT__22)	(struct ilwisscriptLexer_Ctx_struct * ctx);

     void
     (*mT__23)	(struct ilwisscriptLexer_Ctx_struct * ctx);

     void
     (*mT__24)	(struct ilwisscriptLexer_Ctx_struct * ctx);

     void
     (*mT__25)	(struct ilwisscriptLexer_Ctx_struct * ctx);

     void
     (*mT__26)	(struct ilwisscriptLexer_Ctx_struct * ctx);

     void
     (*mT__27)	(struct ilwisscriptLexer_Ctx_struct * ctx);

     void
     (*mT__28)	(struct ilwisscriptLexer_Ctx_struct * ctx);

     void
     (*mT__29)	(struct ilwisscriptLexer_Ctx_struct * ctx);

     void
     (*mT__30)	(struct ilwisscriptLexer_Ctx_struct * ctx);

     void
     (*mT__31)	(struct ilwisscriptLexer_Ctx_struct * ctx);

     void
     (*mT__32)	(struct ilwisscriptLexer_Ctx_struct * ctx);

     void
     (*mT__33)	(struct ilwisscriptLexer_Ctx_struct * ctx);

     void
     (*mT__34)	(struct ilwisscriptLexer_Ctx_struct * ctx);

     void
     (*mT__35)	(struct ilwisscriptLexer_Ctx_struct * ctx);

     void
     (*mT__36)	(struct ilwisscriptLexer_Ctx_struct * ctx);

     void
     (*mT__37)	(struct ilwisscriptLexer_Ctx_struct * ctx);

     void
     (*mT__38)	(struct ilwisscriptLexer_Ctx_struct * ctx);

     void
     (*mT__39)	(struct ilwisscriptLexer_Ctx_struct * ctx);

     void
     (*mT__40)	(struct ilwisscriptLexer_Ctx_struct * ctx);

     void
     (*mT__41)	(struct ilwisscriptLexer_Ctx_struct * ctx);

     void
     (*mT__42)	(struct ilwisscriptLexer_Ctx_struct * ctx);

     void
     (*mT__43)	(struct ilwisscriptLexer_Ctx_struct * ctx);

     void
     (*mT__44)	(struct ilwisscriptLexer_Ctx_struct * ctx);

     void
     (*mT__45)	(struct ilwisscriptLexer_Ctx_struct * ctx);

     void
     (*mT__46)	(struct ilwisscriptLexer_Ctx_struct * ctx);

     void
     (*mT__47)	(struct ilwisscriptLexer_Ctx_struct * ctx);

     void
     (*mT__48)	(struct ilwisscriptLexer_Ctx_struct * ctx);

     void
     (*mT__49)	(struct ilwisscriptLexer_Ctx_struct * ctx);

     void
     (*mT__50)	(struct ilwisscriptLexer_Ctx_struct * ctx);

     void
     (*mT__51)	(struct ilwisscriptLexer_Ctx_struct * ctx);

     void
     (*mT__52)	(struct ilwisscriptLexer_Ctx_struct * ctx);

     void
     (*mT__53)	(struct ilwisscriptLexer_Ctx_struct * ctx);

     void
     (*mT__54)	(struct ilwisscriptLexer_Ctx_struct * ctx);

     void
     (*mT__55)	(struct ilwisscriptLexer_Ctx_struct * ctx);

     void
     (*mT__56)	(struct ilwisscriptLexer_Ctx_struct * ctx);

     void
     (*mT__57)	(struct ilwisscriptLexer_Ctx_struct * ctx);

     void
     (*mT__58)	(struct ilwisscriptLexer_Ctx_struct * ctx);

     void
     (*mT__59)	(struct ilwisscriptLexer_Ctx_struct * ctx);

     void
     (*mT__60)	(struct ilwisscriptLexer_Ctx_struct * ctx);

     void
     (*mT__61)	(struct ilwisscriptLexer_Ctx_struct * ctx);

     void
     (*mT__62)	(struct ilwisscriptLexer_Ctx_struct * ctx);

     void
     (*mT__63)	(struct ilwisscriptLexer_Ctx_struct * ctx);

     void
     (*mT__64)	(struct ilwisscriptLexer_Ctx_struct * ctx);

     void
     (*mID)	(struct ilwisscriptLexer_Ctx_struct * ctx);

     void
     (*mINT)	(struct ilwisscriptLexer_Ctx_struct * ctx);

     void
     (*mFLOAT)	(struct ilwisscriptLexer_Ctx_struct * ctx);

     void
     (*mCOMMENT)	(struct ilwisscriptLexer_Ctx_struct * ctx);

     void
     (*mWS)	(struct ilwisscriptLexer_Ctx_struct * ctx);

     void
     (*mSTRING)	(struct ilwisscriptLexer_Ctx_struct * ctx);

     void
     (*mEXPONENT)	(struct ilwisscriptLexer_Ctx_struct * ctx);

     void
     (*mESC_SEQ)	(struct ilwisscriptLexer_Ctx_struct * ctx);

     void
     (*mEOL)	(struct ilwisscriptLexer_Ctx_struct * ctx);

     void
     (*mTokens)	(struct ilwisscriptLexer_Ctx_struct * ctx);
    const char * (*getGrammarFileName)();
    void            (*reset)  (struct ilwisscriptLexer_Ctx_struct * ctx);
    void	    (*free)   (struct ilwisscriptLexer_Ctx_struct * ctx);
};

// Function protoypes for the constructor functions that external translation units
// such as delegators and delegates may wish to call.
//
ANTLR3_API pilwisscriptLexer ilwisscriptLexerNew         (
pANTLR3_INPUT_STREAM
 instream);
ANTLR3_API pilwisscriptLexer ilwisscriptLexerNewSSD      (
pANTLR3_INPUT_STREAM
 instream, pANTLR3_RECOGNIZER_SHARED_STATE state);

/** Symbolic definitions of all the tokens that the 
lexer
 will work with.
 * \{
 *
 * Antlr will define EOF, but we can't use that as it it is too common in
 * in C header files and that would be confusing. There is no way to filter this out at the moment
 * so we just undef it here for now. That isn't the value we get back from C recognizers
 * anyway. We are looking for ANTLR3_TOKEN_EOF.
 */
#ifdef	EOF
#undef	EOF
#endif
#ifdef	Tokens
#undef	Tokens
#endif
#define EOF      -1
#define T__13      13
#define T__14      14
#define T__15      15
#define T__16      16
#define T__17      17
#define T__18      18
#define T__19      19
#define T__20      20
#define T__21      21
#define T__22      22
#define T__23      23
#define T__24      24
#define T__25      25
#define T__26      26
#define T__27      27
#define T__28      28
#define T__29      29
#define T__30      30
#define T__31      31
#define T__32      32
#define T__33      33
#define T__34      34
#define T__35      35
#define T__36      36
#define T__37      37
#define T__38      38
#define T__39      39
#define T__40      40
#define T__41      41
#define T__42      42
#define T__43      43
#define T__44      44
#define T__45      45
#define T__46      46
#define T__47      47
#define T__48      48
#define T__49      49
#define T__50      50
#define T__51      51
#define T__52      52
#define T__53      53
#define T__54      54
#define T__55      55
#define T__56      56
#define T__57      57
#define T__58      58
#define T__59      59
#define T__60      60
#define T__61      61
#define T__62      62
#define T__63      63
#define T__64      64
#define COMMENT      4
#define EOL      5
#define ESC_SEQ      6
#define EXPONENT      7
#define FLOAT      8
#define ID      9
#define INT      10
#define STRING      11
#define WS      12
#ifdef	EOF
#undef	EOF
#define	EOF	ANTLR3_TOKEN_EOF
#endif

#ifndef TOKENSOURCE
#define TOKENSOURCE(lxr) lxr->pLexer->rec->state->tokSource
#endif

/* End of token definitions for ilwisscriptLexer
 * =============================================================================
 */
/** } */

#ifdef __cplusplus
}
#endif

#endif

/* END - Note:Keep extra line feed to satisfy UNIX systems */
