#ifndef ILWISCOREUI_GLOBAL_H
#define ILWISCOREUI_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ILWISCOREUI_LIBRARY)
#  define ILWISCOREUISHARED_EXPORT Q_DECL_EXPORT
#else
#  define ILWISCOREUISHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // ILWISCOREUI_GLOBAL_H
