#ifndef BASEOPERATIONS_GLOBAL_H
#define BASEOPERATIONS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(BASEOPERATIONS_LIBRARY)
#  define BASEOPERATIONSSHARED_EXPORT Q_DECL_EXPORT
#else
#  define BASEOPERATIONSSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // RASTERAPPLICATIONS_GLOBAL_H
