#ifndef RASTEROPERATIONS_GLOBAL_H
#define RASTEROPERATIONS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(RASTERRASTEROPERATIONS_LIBRARY)
#  define RASTEROPERATIONSSHARED_EXPORT Q_DECL_EXPORT
#else
#  define RASTEROPERATIONSSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // RASTERAPPLICATIONS_GLOBAL_H
